<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-11-22T09:33:51+04:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Asia/Dubai',
];
