<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-11-22T09:34:48+04:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Concrete5-8',
        ],
    ],
];
